### PR TITLE
Ability to replace text with Preserve Case

### PR DESCRIPTION
**Pull request by d0vgan**
Ability to replace text with Preserve Case, similarly to VS Code.
This pull request implements the enhancement https://github.com/Alexey-T/CudaText/issues/4825

### CODE REVIEW

**Comment by Alexey-T** [comment]
Will review it soon.
question: what if 'found text' has length N and 'replace with' has length M<>N ? your code works?

**Review by Alexey-T — APPROVED** [review]

**Comment by d0vgan** [comment]
> what if 'found text' has length N and 'replace with' has length M<>N ? your code works?

Yes, it works.

**Comment by Alexey-T** [comment]
question: if found-text is 'fSomeNameABC' and replace-with is 'Gsomenameppp' - your code gives 'gSomeNamePPP' ?

**Comment by d0vgan** [comment]
> question: if found-text is 'fSomeNameABC' and replace-with is 'Gsomenameppp' - your code gives 'gSomeNamePPP' ?

No, it gives 'gsomenameppp', exactly as VS Code does for mixed-case original strings.
The VS Code's logic is:
- In case of all capital or all lower-case characters in the original string, the result exactly follows the original string: it will be either all capital or all lower-case.
- In case of a first capital character in the original string, the first character in the result will be capital.
- In case of a first lower-case character in the original string, the first character in the result will be lower-case.
- In case of mixed case in the original string, the result follows the case of the characters in the replacing string (excluding the very first character of the original string that always preserves its original case).

We may change the logic if we want.

**Comment by Alexey-T** [comment]
Ok, thanks, it is good for me. pls, work with your new code some days, and then i will apply it.

**Comment by Alexey-T** [comment]
let's include this bug comment near the begin of GetPreserveCaseReplacement:
```
The VS Code's logic is:

    In case of all capital or all lower-case characters in the original string, the result exactly follows the original string: it will be either all capital or all lower-case.
    In case of a first capital character in the original string, the first character in the result will be capital.
    In case of a first lower-case character in the original string, the first character in the result will be lower-case.
    In case of mixed case in the original string, the result follows the case of the characters in the replacing string (excluding the very first character of the original string that always preserves its original case).
```

**Comment by Alexey-T** [comment]
@d0vgan 
seems it's better to use funcs from Character unit
```
    class function IsLetter(AChar : UnicodeChar) : Boolean; overload; static; inline;
    class function IsLetterOrDigit(AChar : UnicodeChar) : Boolean; overload; static; inline;
```
because my IsWordChar returns True for digits and '_'. for some rarely user Unicode letters (eg. Arabic) results from my function and from FPC function may be not the same..... so better use FPC func.

**Comment by Alexey-T** [comment]
these 2 a 'class functions' so to call them: TCharacter.IsLetter('a')

**Comment by d0vgan** [comment]
>  my IsWordChar returns True for digits and '_'.

Usually text editor specifies its own rules for what is treated as a word character and what is not. These rules are also language-specific: for example, "$" is word character for PowerShell and AWK whereas it can be a word separator in some other languages.

**Comment by Alexey-T** [comment]
yes, and to detect 'is word char' with knowing of special symbols, ATSynEdit has separate function IsWordChar (or IsCharWord?) with additional 2nd argument "string of non-word chars".
atsynedit_finder don't know this function.
so it is safe to replace my IsWordChar to TCharacter.IsLetter

**Comment by d0vgan** [comment]
> so it is safe to replace my IsWordChar to TCharacter.IsLetter

The purpose of the first loop is to skip all non-word characters to make `i` to point to a first character of a word. (for example, `7th` is a word in e.g. ` , 7th`)
Correspondingly, the first loop can be either
```
i := 1;
while i <= inputLen do
begin
  if TCharacter.IsWhiteSpace(AFromText[i]) or TCharacter.IsPunctuation(AFromText[i]) or TCharacter.IsSeparator(AFromText[i]) then
    Inc(i); // skipping non-word characters
  else
    break
end;
```
or it can be
```
i := 1;
while i <= inputLen do
begin
  if IsWordChar(AFromText[i]) then
    break
  else
    Inc(i); // skipping non-word characters
end;
```
The second version looks more efficient.

**Pull request merged**
