### PR TITLE
fix #195 - User commands should have a constant where to start

### LINKED ISSUE #195: User commands should have a constant where to start
It's about adding a constant that users can use as base for their custom commands. I'd suggest 8000 but it doesn't matter as long as it prevents clearly users to use a value that could conflict with internal AT commands.

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by Alexey-T** [comment]
User commds can be from 100k.. or 10k. Or 8k. Or 6k. Hmm

**Comment by Alexey-T** [comment]
Not sure any user will find this id

**Comment by BBasile** [comment]
example:

```pascal
procedure TmyEditor.DoCommand(ACmd: integer; const AText: atString = '');
begin
  inherited;  // may process 1000
  case ACmd of
      1000: begin doMyCustom1000thCOmmand end;
  end;
end;
```

**Comment by BBasile** [comment]
SynEdit has a clear number where people can start numbering their commands.

**Comment by Alexey-T** [comment]
You can use 8000, not sure const is needed

**Comment by BBasile** [comment]
> Not sure any user will find this id

I found it and use it with TSynEdit. It's about a convention. When the const is here people have no excuse if they make the error.

**Comment by BBasile** [comment]
See https://github.com/alrieckert/lazarus/blob/master/components/synedit/syneditkeycmds.pp#L279

**Comment by BBasile** [comment]
It's not okay to refuse this Alexey. You came a first time, 2 years ago, proposing to use it. I said no. You came again last month saying "use ATSynEdit, do this do that". I've said okay and now that i try, my requirements are not reasonable ? I really can keep on using TSynEdit, it works, it's comfy, it's the comfort zone. **You** came to me asking, proposing.

**Comment by BBasile** [comment]
I can delete the feature branch and "poof" i'll forget the guy who contacted me two times to use his library and **refused once a stupid constant**.

**Comment by Alexey-T** [comment]
OK, can you pls change constant to 8000, i will accept it.

**Comment by BBasile** [comment]
No 100000 leaves you some room. It's a perfectly reasonable number.

**Comment by Alexey-T** [comment]
I thhoght you can add constant to **your code**

**Comment by BBasile** [comment]
yes, thanks buddy.

**Comment by BBasile** [comment]
Sorry, while i appreciated this, switch are fucked up now. In other words, i've made an error. 

> ce_editor.pas(722,24) Error: range check error while evaluating constants (100002 must be between 0 and 65535)

30000 then... do you update or do i have to make a PR ?

**Comment by BBasile** [comment]
Damn, i didn't know this limitation of Pascal.

**Comment by Alexey-T** [comment]
I accept PR.

**Comment by BBasile** [comment]
Thx buddy.

**Pull request merged**
