### PR TITLE
Fix for IBUS IM

### PR DESCRIPTION
**Pull request by rasberryrabbit**
It is partial fix for IBUS IM.
It requires new patch at [fpc/lazarus bug tracker #38730](https://bugs.freepascal.org/view.php?id=38730)

It make possible working on IBUS IM. But there is one limitation.
Pre-Selected-Block manipulation cannot works properly. It's only IBUS IM limitation. 
fcitx IM works good with it.

### CODE REVIEW

**Comment by Alexey-T** [comment]
I wait until linked Laz patch is applied.

**Comment by Alexey-T** [comment]
@rasberryrabbit 
I got a question from Martin. please tell me, I will tell him:

Q:
Btw, if you have knowledge how to:
- activate the IM (Ubuntu, Fedora or Mint / all Gnome, I think -> the installer did not ask)
- trigger the old double keystroke issue
I would appreciate a note on the topic. 
I mainly tried on Mint, but was unable to get any IM to trigger.

**Comment by rasberryrabbit** [comment]
Activating the IM is simple.
```
sudo apt-get update -y
sudo apt-get install -y ibus
```
And
IM selection menu in Ubuntu "Language Support" Section. It need reboot after changing.

I haven't got double keystroke issue with patch. 
I remember that it happens with triggering both 'commit_cb' callback and internal keypress emulation code(commit_cb callback first and keypress emulation second).
It suppressed by patch, it doesn't be triggered currently.

**Comment by Alexey-T** [comment]
thanks, applied.

**Pull request merged**
