### PR TITLE
Fix econtrol dependency

### PR DESCRIPTION
**Pull request by BBasile**
the demo can now be tested using EControl submodule. Previously this couln't work !

### CODE REVIEW

**Comment by Alexey-T** [comment]
Seems ok; don't know submodules. tks..

**Comment by BBasile** [comment]
users like me who follow the project from git doesn't necessarily have the same file system layout. so when they clone ATSynEdit, if they type
`git submodule update`
`git submodule init`
econtrol is copied in their repo. without this, we couldn't run the demo with highlighter, because the project was referencing some absolute path like on your system: E:\...

**Comment by BBasile** [comment]
Note that you'll have to update the submodule EControl too, for example this evening the **demo_adapter_econtrol** doesn't compile anymore because of that.
when you've updated EControl repository, execute this in ATSynEdit:

> git submodule foreach git pull

this update the submodule to match the state in the original repo. Then when you commit in TASynEdit,
commit the submodule update by typing:

> git add EControl
> git commit -m 'any message'
> git push

You can try the software SourceTree, which helps to do this in GUI mode.
(https://www.sourcetreeapp.com/)

**Comment by Alexey-T** [comment]
I tried, I did command you post, and one cmd worked and 2nd don't work (git shows err "cannot push.....................") so Cant use it; I don't use git, i use Tortoise

**Comment by BBasile** [comment]
I'm sorry, I think i lead you into a brick wall...i didn't know you use SVN.
You can revert the PR if you like, or i'll send another PR to revert the PR.

**Comment by Alexey-T** [comment]
Hm not svn. I use Tortoise Git. I cannot easy do "git.exe ....." but i wrote path to git .exe, command worked with error (don't send PR)

**Pull request merged**
