### PR TITLE
linux fcitx IM patch

### PR DESCRIPTION
**Pull request by rasberryrabbit**
It need last patch at bugtrakcer.
[https://bugs.freepascal.org/view.php?id=38730](url)

It's experimental. Not fully tested.
It works under ubuntu i386.

### CODE REVIEW

**Comment by Alexey-T** [comment]
Pleas test this during several days, at least, to be sure.

**Comment by Alexey-T** [comment]
`        Carets.AsString;  // this dummy need to work. bug?`
What?
It does only this so I dont understand how it helps--
```
function TATCarets.GetAsString: string;
var
  Item: TATCaretItem;
  S: string;
  NLast, i: integer;
begin
  Result:= '';
  NLast:= Count-1;
  for i:= 0 to NLast do
  begin
    Item:= Items[i];
    if Item.EndY<0 then
      S:= Format('%d,%d', [Item.PosX, Item.PosY])
    else
      S:= Format('%d,%d,%d,%d', [Item.PosX, Item.PosY, Item.EndX, Item.EndY]);
    if i<NLast then
      S+= ';';
    Result+= S;
  end;
end; 
```

**Comment by rasberryrabbit** [comment]
I also surprise. However it works on my machine. It may fpc trunk compiler bug.

**Comment by Alexey-T** [comment]
OK.
1-- I wait until Laz dev's apply their Laz patch
2-- I will make the beta of CudaText and users will test it

**Comment by Alexey-T** [comment]
let's test it more.
@rasberryrabbit Can you compile test version of Cud and post it to your Github 'releases'? we will ask users to test it.

**Comment by rasberryrabbit** [comment]
Miss using API makes dummy code problem.

In gtk2globals.pp ,
```
procedure IM_Context_Set_Cursor_Pos(X, Y: gint);
var
  CurPos: TGdkRectangle;
begin
  CurPos.x:=X;
  CurPos.y:=Y;
  CurPos.width:=0; // fix invalid candidate window position
  CurPos.height:=0;
  gtk_im_context_set_cursor_location(im_context,@CurPos);
end;
```

It fix dummy problem.

**Comment by rasberryrabbit** [comment]
I have small virtual machine space, it's hard to build test release. Sorry.

**Comment by Alexey-T** [comment]
@rasberryrabbit that patch for GTK2 file-- don't post here. I will not apply patches to Laz from here. I will wait when patches come to Lazarus. So post this GTK2 fix to that Lazarus issue.

**Comment by Alexey-T** [comment]
@rasberryrabbit Pls do more testing for IME patch. if you can, write to the Laz bugtracker to support Laz patch for IME.

**Comment by Alexey-T** [comment]
@rasberryrabbit Now Lazarus dev committed their patch here
https://bugs.freepascal.org/view.php?id=38730
it will be good if you can download FpcUpDeluxe, install __Lazarus trunk__, and test IME under your linux.
if you don't want to get Lazarus I will prepare some test Cudatext builds.

**Comment by rasberryrabbit** [comment]
With new official patch, IM works good.

**Comment by Alexey-T** [comment]
applied patch with minor changes. new beta here
http://www.uvviewsoft.com/c/
test and confirm it's OK

**Comment by Alexey-T** [comment]
@rasberryrabbit Pls see https://github.com/Alexey-T/CudaText/issues/3442#issuecomment-862334048

**Pull request merged**
