### PR TITLE
Fix blocked text multicarets insertion.

### PR DESCRIPTION
**Pull request by rasberryrabbit**
Fix Blocked text multicarets text insertion by preventing removing duplicated caret position after multicarets block deletion.

```
bb bb b b
12 34 5 6
^^ ^^ ^ ^
block deleted and sort carets, duplicated caret deleted ->
1 3 5 6
^ ^ ^ ^
```

### CODE REVIEW

**Comment by Alexey-T** [comment]
You restored Textinsertatcarets with empty string. But textinsert...... must not be called with empty str. It is bad cause it joins caret which have neatest selections. So, avoid this call. Call it with ready text

**Comment by rasberryrabbit** [comment]
DoCommand_TextDeleteSelection removes carets before text insertion. 
This function don't affect removing carets by Empty string parameter.

**Comment by Alexey-T** [comment]
DoCommand_TextDeleteSelection is now not called inside TextInsertAtCarets, which was the new fix. TextInsertAtCarets replaces selections with new text mare careful.

**Comment by rasberryrabbit** [comment]
It doesn't updated, git still has disabled IM.

**Comment by Alexey-T** [comment]
I don’t understand you...

**Comment by rasberryrabbit** [comment]
You mentioned 'DoCommand_TextDeleteSelection is now not called inside TextInsertAtCarets, which was the new fix'.
But master copy still has no changes. Bug on Git?

**Comment by Alexey-T** [comment]
Master has it! see https://github.com/Alexey-T/ATSynEdit/commit/c68d4f57ff855e59661a9402480f9ac1f9b356f8
where I delete call 
`DoSelectionDeleteOrReset;`
which cleared the selection and joined carets!

**Comment by rasberryrabbit** [comment]
My apologies. But still remains 'exit' IM handler. Is it still buggy?

**Comment by Alexey-T** [comment]
Yes, if I enable that handler the issue will return- 3442. Don’t you see this?

**Comment by rasberryrabbit** [comment]
Ok. I make preventing null string insertion on IM handler.

**Comment by Alexey-T** [comment]
Is that change in atsynedit_carets.pas needed? I revert this change.

**Comment by rasberryrabbit** [comment]
It don't need anymore. It can revert it.

**Pull request merged**
