### PR TITLE
Fix string index in caret drawing.

### PR DESCRIPTION
**Pull request by rasberryrabbit**
It is actually dead code, cursor position always returns 0 from input method.

### CODE REVIEW

**Review by Alexey-T — APPROVED** [review]

**Comment by Alexey-T** [comment]
@rasberryrabbit 
About your fix, i made Lazarus forum topic.
https://forum.lazarus.freepascal.org/index.php?topic=65417.0
Juha asked a question there, pls see.

**Comment by rasberryrabbit** [comment]
I got hint from other source code, but it make bad behavier on lazarus.

**Comment by Alexey-T** [comment]
So that fix is not needed? If it is needed - for what?

**Comment by rasberryrabbit** [comment]
If form lost focus out of application then input method also signal end composition but it doesn't.
And application's composition form still remains.  
I try to fix that but fails.  

It may Child focused control doesn't call DoExit when application lost control on GTK.

**Pull request merged**
