### PR TITLE
Get more info from IME.

### PR DESCRIPTION
**Pull request by rasberryrabbit**
Get more info from IME.
But chinese candidate caret moving is still not implemented.

I get position, IME returns updated composition string but I can't rendering caret at position. 
I guess adding composition modaless form for IME is better idea.

### CODE REVIEW

**Comment by Alexey-T** [comment]
To show the caret lefter than candidate, I suggest to use Ed.Attribs object (you can add temporary attrib with Tag=-3, which highlights needed part of text; later you can do Ed.Attribs.DeleteWithTag).

**Comment by Alexey-T** [comment]
Please resolve the conflicts, I just did the big change.

**Comment by rasberryrabbit** [comment]
I try to make another method. It draw pesudo caret on Composition form.

**Comment by Alexey-T** [comment]
Github shows: `This branch has conflicts that must be resolved`. Pls resolve them.

'try/except' is not needed in new diff.

**Comment by rasberryrabbit** [comment]
Sorry, I fogot merge from upstream.

**Comment by Alexey-T** [comment]
Thanks. Can you please give precompiled Win64 .exe ? I will give the link to user to test.

**Comment by rasberryrabbit** [comment]
Win64 test exe file.
[project1_atsynedit.zip](https://github.com/Alexey-T/ATSynEdit/files/11365792/project1_atsynedit.zip)

**Comment by rasberryrabbit** [comment]
Win64 test exe file.

[project1_atsynedit_2.zip](https://github.com/Alexey-T/ATSynEdit/files/11369849/project1_atsynedit_2.zip)

**Comment by Alexey-T** [comment]
Do you have a possibility to test it on older Windows,to see user's issue, please?

**Comment by Alexey-T** [comment]
I will wait few days and will apply this PR. thank you for support.

**Comment by Alexey-T** [comment]
@rasberryrabbit I made changes in atsynedit for CudaText 1.193 and now your fork needs the updating...

**Pull request merged**
