### PR TITLE
Get more accuracy FullCharScale.

### PR DESCRIPTION
**Pull request by rasberryrabbit**
Calc more accuracy FullCharScale with Font and Linux Support.

### CODE REVIEW

**Comment by Alexey-T** [comment]
Can u make constants for "M" and for unicode cjk char? also for utf8 cjk char. all chars make constants.

Can u add URL to unicode site about your Unicode code (url to info about char)

**Comment by rasberryrabbit** [comment]
Sorry, I'm late. 
https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms
Full width char 'M' is useful on most cases :)

**Comment by Alexey-T** [comment]
i mean not this
i mean: pls make code of M and of Korean char as 

const
cCodeM = maybe $20+$2d
cCodeKorean = $FF00+.....

**Comment by rasberryrabbit** [comment]
Aha, last value is alphabet order,
```
const
  cCodeM = $20+$2d
  cCodeCJKM = $FF00+$2d
```

**Comment by Alexey-T** [comment]
need const. here too-

    ATStringProc.cCharScaleFullwidth := Canvas.GetTextWidth(#$ef#$bc#$ad) / Canvas.GetTextWidth('M');

const for 'M' and for Utf8encode(some char).

**Comment by rasberryrabbit** [comment]
Yep :)

**Pull request merged**
